/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Control.Data;
import Model.ConexaoComb;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author PHAIMBNOT003
 */
public class JpanelComb extends javax.swing.JPanel {
    int contclick=0;
    public String nomes, produtos, produtos1, produtos2, produtos3, produtos4;
    /**
     * Creates new form JpanelComb
     */
    public JpanelComb() {
        initComponents();
        Data data = new Data();
        jDateChooserInicial.setDate(data.getPegaDataAtual());
        jDateChooserFinal.setDate(data.getPegaDataAtual());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextFieldSub1 = new javax.swing.JTextField();
        jTextFieldSub2 = new javax.swing.JTextField();
        jTextFieldSub3 = new javax.swing.JTextField();
        jTextFieldSub4 = new javax.swing.JTextField();
        jTextFieldSub5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonRelatorio = new javax.swing.JButton();
        jDateChooserInicial = new com.toedter.calendar.JDateChooser();
        jDateChooserFinal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo2.png"))); // NOI18N

        setPreferredSize(new java.awt.Dimension(575, 542));
        setRequestFocusEnabled(false);

        jLabel1.setText("Codigo:");

        jLabel2.setText("Descrição:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField2.setEnabled(false);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.setEnabled(false);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField4.setEnabled(false);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField5.setEnabled(false);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jTextFieldSub1.setEditable(false);
        jTextFieldSub1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSub1.setEnabled(false);
        jTextFieldSub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSub1ActionPerformed(evt);
            }
        });

        jTextFieldSub2.setEditable(false);
        jTextFieldSub2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSub2.setEnabled(false);
        jTextFieldSub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSub2ActionPerformed(evt);
            }
        });

        jTextFieldSub3.setEditable(false);
        jTextFieldSub3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSub3.setEnabled(false);

        jTextFieldSub4.setEditable(false);
        jTextFieldSub4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSub4.setEnabled(false);
        jTextFieldSub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSub4ActionPerformed(evt);
            }
        });

        jTextFieldSub5.setEditable(false);
        jTextFieldSub5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSub5.setEnabled(false);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonRemove.setText("Remover");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jButtonRelatorio.setText("Relatório");
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });

        jDateChooserInicial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jDateChooserFinal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setText("Data Inicial:");

        jLabel6.setText("Data Final:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Combinações de Substâncias");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1)
                        .addComponent(jTextField2)
                        .addComponent(jTextField3)
                        .addComponent(jTextField4)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldSub1)
                        .addComponent(jTextFieldSub3)
                        .addComponent(jTextFieldSub4)
                        .addComponent(jTextFieldSub5)
                        .addComponent(jTextFieldSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jDateChooserInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jDateChooserFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(167, 167, 167)
                            .addComponent(jLabel6))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSub5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextFieldSub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSub1ActionPerformed

    private void jTextFieldSub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSub2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSub2ActionPerformed

    private void jTextFieldSub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSub4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSub4ActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        // TODO add your handling code here:
        if(contclick==1){
            jTextField2.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField2.setText("");
            jTextFieldSub2.setText("");
            
            contclick--;
        }else if(contclick==2){
            
            
            jTextField3.setEnabled(false);
            jTextField3.setEnabled(false);
            jTextField3.setText("");
            jTextFieldSub3.setText("");
            
            contclick--;
        }else if(contclick==3){
            
            
            jTextField4.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField4.setText("");
            jTextFieldSub4.setText("");
            
            contclick--;
        }else if(contclick==4){
            
            
            jTextField5.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField5.setText("");
            jTextFieldSub5.setText("");
            
            contclick--;
        }else if( contclick==0){
        
            JOptionPane.showMessageDialog(null, "Não é possivel Remover mais.");
        
        }
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(contclick==0){
            jTextField2.setEnabled(true);
            jTextField2.setEditable(true);
            
            contclick++;
            
        }else if(contclick==1){
            jTextField3.setEnabled(true);
            jTextField3.setEditable(true);
            
            contclick++;
        
        }else if(contclick==2){
            jTextField4.setEnabled(true);
            jTextField4.setEditable(true);
            
            contclick++;
        
        }else if(contclick==3){
            jTextField5.setEnabled(true);
            jTextField5.setEditable(true);
            
            contclick++;
        
        }else if(contclick == 4){
        
            JOptionPane.showMessageDialog(null, "Não é possivel adicionar mais.");
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed
        // TODO add your handling code here:
        if ( jTextFieldSub1.getText().trim().equals("") ){
            
            
            System.err.println("Nenhuma Substancia Selecionada!");
        
            JOptionPane.showMessageDialog(null, "Selecione uma substância, antes de gerar o Relatório!");
        
            
        
        } else {
            
            if(( contclick==0 )){
            
                nomes = produtos;
                
                SimpleDateFormat out = new SimpleDateFormat("dd.MM.yyyy");
                String dtinicial = out.format(jDateChooserInicial.getDate());
                String dtfinal = out.format(jDateChooserFinal.getDate());
            
                ConexaoComb cn1 = new ConexaoComb();
                
                try {
                    cn1.consultaRQ1(Integer.parseInt(jTextField1.getText()), dtinicial, dtfinal, nomes);
                } catch (SQLException | JRException ex) {
                    Logger.getLogger(JpanelComb.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            }
            
            if ( contclick == 1 ) {
                nomes = produtos + " e " + produtos1;
                SimpleDateFormat out = new SimpleDateFormat("dd.MM.yyyy");
                String dtinicial = out.format(jDateChooserInicial.getDate());
                String dtfinal = out.format(jDateChooserFinal.getDate());

                ConexaoComb cn1 = new ConexaoComb();
                
                try {

                    cn1.consultaRQ2(Integer.parseInt(jTextField1.getText()), Integer.parseInt(jTextField2.getText()), dtinicial, dtfinal, nomes);

                } catch (SQLException | JRException ex) {
                    Logger.getLogger(JpanelComb.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (contclick == 2) {
                nomes = produtos + ", " + produtos1 + " e " + produtos2;
                SimpleDateFormat out = new SimpleDateFormat("dd.MM.yyyy");
                String dtinicial = out.format(jDateChooserInicial.getDate());
                String dtfinal = out.format(jDateChooserFinal.getDate());

                ConexaoComb cn1 = new ConexaoComb();
                try {

                    cn1.consultaRQ3(Integer.parseInt(jTextField1.getText()), Integer.parseInt(jTextField2.getText()), Integer.parseInt(jTextField3.getText()), dtinicial, dtfinal, nomes);

                } catch (SQLException | JRException ex) {
                    Logger.getLogger(JpanelComb.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            } else if (contclick == 3) {
                nomes = produtos+", "+produtos1+", "+produtos2+" e "+produtos3;
                SimpleDateFormat out = new SimpleDateFormat("dd.MM.yyyy");
                String dtinicial = out.format(jDateChooserInicial.getDate());
                String dtfinal = out.format(jDateChooserFinal.getDate());

                ConexaoComb cn1 = new ConexaoComb();
                try {

                    cn1.consultaRQ4(Integer.parseInt(jTextField1.getText()), Integer.parseInt(jTextField2.getText()), Integer.parseInt(jTextField3.getText()), Integer.parseInt(jTextField4.getText()), dtinicial, dtfinal, nomes);

                } catch (SQLException | JRException ex) {
                    Logger.getLogger(JpanelComb.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (contclick == 4) {
                nomes = produtos+", "+produtos1+ ", "+ produtos2+", "+produtos3+" e "+produtos4;
                
                SimpleDateFormat out = new SimpleDateFormat("dd.MM.yyyy");
                String dtinicial = out.format(jDateChooserInicial.getDate());
                String dtfinal = out.format(jDateChooserFinal.getDate());

                ConexaoComb cn1 = new ConexaoComb();
                try {

                    cn1.consultaRQ5(Integer.parseInt(jTextField1.getText()), Integer.parseInt(jTextField2.getText()), Integer.parseInt(jTextField3.getText()), Integer.parseInt(jTextField4.getText()), Integer.parseInt(jTextField5.getText()), dtinicial, dtfinal, nomes);

                } catch (SQLException | JRException ex) {
                    Logger.getLogger(JpanelComb.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        

        }
    }//GEN-LAST:event_jButtonRelatorioActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            ConexaoComb cc = new ConexaoComb();

            try {
                
                produtos = cc.buscarSubstancia(Integer.parseInt(jTextField1.getText()));
                
                jTextFieldSub1.setText(produtos);
                
                
            } catch (SQLException ex) {
                
                Logger.getLogger(JpanelComb.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("O erro foi aqui no jtextfield");
                
            }

        }
        
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            ConexaoComb cc = new ConexaoComb();

            try {
                
                produtos1 = cc.buscarSubstancia(Integer.parseInt(jTextField2.getText()));
                
                jTextFieldSub2.setText(produtos1);
                
                
            } catch (SQLException ex) {
                Logger.getLogger(JpanelComb.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("O erro foi aqui no jtextfield");
            }

        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            ConexaoComb cc = new ConexaoComb();

            try {
                
                produtos2 = cc.buscarSubstancia(Integer.parseInt(jTextField3.getText()));
                
                jTextFieldSub3.setText(produtos2);
                
                
            } catch (SQLException ex) {
                Logger.getLogger(JpanelComb.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("O erro foi aqui no jtextfield");
            }

        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            ConexaoComb cc = new ConexaoComb();

            try {
                
                produtos3 = cc.buscarSubstancia(Integer.parseInt(jTextField4.getText()));
                
                jTextFieldSub4.setText(produtos3);
                
                
            } catch (SQLException ex) {
                Logger.getLogger(JpanelComb.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("O erro foi aqui no jtextfield");
            }

        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            ConexaoComb cc = new ConexaoComb();

            try {
                
                produtos4 = cc.buscarSubstancia(Integer.parseInt(jTextField5.getText()));
                
                jTextFieldSub5.setText(produtos4);
                
                
            } catch (SQLException ex) {
                Logger.getLogger(JpanelComb.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("O erro foi aqui no jtextfield");
            }

        }
    }//GEN-LAST:event_jTextField5KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JButton jButtonRemove;
    private com.toedter.calendar.JDateChooser jDateChooserFinal;
    private com.toedter.calendar.JDateChooser jDateChooserInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldSub1;
    private javax.swing.JTextField jTextFieldSub2;
    private javax.swing.JTextField jTextFieldSub3;
    private javax.swing.JTextField jTextFieldSub4;
    private javax.swing.JTextField jTextFieldSub5;
    // End of variables declaration//GEN-END:variables
}
